import {
  copyFileSync,
  type Dirent,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import vike from 'vike/plugin';
import { defineConfig, type Plugin } from 'vite';

/**
 * Mirror repo-owned assets into `public/` at the start of every dev/build run.
 *
 * Both sources are owned by other tickets; we only READ them, and both
 * destinations are gitignored build artifacts, so nothing is duplicated in
 * source control.
 *
 *   `docs/*.schema.json`        -> `/schemas/*.json`
 *     Stable static URLs an editor's `$schema` key can point at.
 *
 *   `dev-docs/ui-screenshots/<id>/<os>-<appearance>.png`
 *                              -> `/ui/<id>-<os>-<appearance>.png`
 *     The screenshot fixtures generated by `tests/ui_screenshots.rs`. The docs
 *     illustrate themselves with the same PNGs the test harness renders, so a
 *     screenshot can never drift from the UI it documents — regenerating the
 *     fixtures republishes the docs images.
 *
 *     The source is foldered per fixture so a fixture's six renders and the
 *     `layout.json` describing them travel together in a diff; the published
 *     URLs stay flat, because they are the site's public surface and a
 *     reorganisation of the repo is not a reason to break a link someone
 *     saved. Flattening happens here, in the one place that knows both shapes.
 */
function copyRepoAssets(): Plugin {
  return {
    name: 'secreq-copy-repo-assets',
    buildStart() {
      const repoRoot = join(process.cwd(), '..');
      const publicDir = join(process.cwd(), 'public');

      const schemaDest = join(publicDir, 'schemas');
      mkdirSync(schemaDest, { recursive: true });
      for (const file of ['wraps.schema.json', 'auto-rules.schema.json']) {
        try {
          copyFileSync(join(repoRoot, 'docs', file), join(schemaDest, file));
        } catch {
          console.warn(`[docs-site] Could not copy schema ${file}`);
        }
      }

      // The install script the site's headline command pipes into a shell.
      // Both the landing page and `docs/install.md` print
      // `curl -fsSL https://craigory.dev/secreq/install.sh | sh`, and until this
      // existed nothing published the script — the most prominent command on
      // the site fetched the 404 page and piped it to `sh`.
      //
      // Copied from the repo rather than duplicated into `public/` so there is
      // one install script: the one `scripts/package-release.sh` ships inside
      // the release tarball is the one the site serves.
      try {
        copyFileSync(join(repoRoot, 'dist', 'install.sh'), join(publicDir, 'install.sh'));
      } catch {
        console.warn('[docs-site] Could not copy dist/install.sh — the site will 404 on it');
      }

      const shotSrc = join(repoRoot, 'dev-docs', 'ui-screenshots');
      const shotDest = join(publicDir, 'ui');
      mkdirSync(shotDest, { recursive: true });

      const renders = discoverRenders(shotSrc);

      // Mirror, don't merge. Copying without pruning meant a renamed or
      // deleted fixture kept being published forever — the destination is a
      // gitignored build artifact, so it should reflect the source exactly
      // rather than accumulate every render this checkout has ever seen.
      const wanted = new Set([...renders.map(publicName), ...renders.map(sceneName)]);
      for (const stale of readdirSync(shotDest)) {
        if (!wanted.has(stale)) rmSync(join(shotDest, stale), { force: true });
      }
      for (const render of renders) {
        copyFileSync(join(shotSrc, render), join(shotDest, publicName(render)));
      }
      if (renders.length === 0) {
        console.warn('[docs-site] No UI screenshots copied — figures will 404');
      }

      writeShotIndex(shotSrc, renders);
      writeScenes(shotSrc, shotDest, renders);
      writeTermIndex(join(repoRoot, 'dev-docs', 'cli-transcripts'));
    },
  };
}

/**
 * Bundle the recorded terminal sessions for the app to import.
 *
 * Each recording is one self-describing JSON written by
 * `tests/cli_transcripts.rs`, so the index is just those files keyed by id —
 * a recording, unlike a PNG, can carry its own metadata. The `.txt`
 * companions beside them are for reviewing diffs and are deliberately not
 * published.
 */
function writeTermIndex(termSrc: string) {
  const index: Record<string, unknown> = {};

  let files: string[] = [];
  try {
    files = readdirSync(termSrc).filter((file) => file.endsWith('.json'));
  } catch {
    console.warn(
      '[docs-site] No CLI transcripts yet — record them with ' +
        '`cargo test --test cli_transcripts -- --ignored --test-threads=1`.',
    );
  }

  for (const file of files) {
    try {
      const doc = JSON.parse(readFileSync(join(termSrc, file), 'utf-8'));
      const id = doc.id ?? file.replace(/\.json$/, '');
      index[id] = doc;
    } catch {
      console.warn(`[docs-site] Could not read transcript ${file}`);
    }
  }

  const outDir = join(process.cwd(), '.generated');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'terms.json'), JSON.stringify(index, null, 2) + '\n');
}

/**
 * Every render in the screenshot tree, as its `<id>/<variant>.png` path.
 *
 * One level deep, and only inside a fixture's folder: a directory here *is* a
 * fixture, so a PNG loose in the screenshot root belongs to none of them and is
 * not published just because it happens to sit there. Anything in a fixture's
 * folder that isn't a `.png` — its `layout.json` — is left where it is; the
 * folder is the fixture's, not the site's.
 */
function discoverRenders(shotSrc: string): string[] {
  const found: string[] = [];
  let entries: Dirent[] = [];
  try {
    entries = readdirSync(shotSrc, { withFileTypes: true });
  } catch {
    console.warn(`[docs-site] Could not read screenshots from ${shotSrc}`);
    return found;
  }

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    for (const file of readdirSync(join(shotSrc, entry.name))) {
      if (file.endsWith('.png')) found.push(`${entry.name}/${file}`);
    }
  }
  return found.sort();
}

/** `02-single-pending/macos-dark.png` -> `02-single-pending-macos-dark.png`. */
function publicName(render: string): string {
  return render.replace('/', '-');
}

/** The same cell's geometry: `02-single-pending-macos-dark.json`. */
function sceneName(render: string): string {
  return publicName(render).replace(/\.png$/, '.json');
}

/**
 * Publish each cell of the matrix as its own geometry file, beside the
 * render it describes.
 *
 * `<secreq-window>` rebuilds a captured window as DOM, and the shapes it
 * needs are already in the fixture's `layout.json`. What it must not do is
 * *import* them: the corpus is some three megabytes across thirty-six
 * fixtures, and a page showing one window would carry all of it. So the
 * one file per fixture that git wants — six variants together, diffable
 * as a unit — is split into the six files a reader wants, and the element
 * fetches the single cell matching their desktop.
 *
 * Written flat, under the screenshot's own name with a `.json` extension,
 * so a window and the screenshot it stands in front of are the same URL
 * twice and cannot be made to disagree about which render they are.
 *
 * The digest goes no further than the repo. It exists so a Rust test
 * failure has one short thing to compare; nothing in a browser can act
 * on it, and it would be a kilobyte per cell on the wire.
 */
function writeScenes(shotSrc: string, shotDest: string, renders: string[]) {
  const byFixture = new Map<string, string[]>();
  for (const render of renders) {
    const parsed = parseRenderPath(render);
    if (!parsed) continue;
    const [id, os, appearance] = parsed;
    byFixture.set(id, [...(byFixture.get(id) ?? []), `${os}-${appearance}`]);
  }

  for (const [id, variants] of byFixture) {
    // A fixture with no `layout.json` has already been reported by
    // `writeShotIndex`, and it publishes as a plain screenshot: no
    // geometry, so the element leaves the PNG where it is.
    const record = readFixtureRecord(shotSrc, id);
    if (!record?.variants) continue;

    for (const variant of variants) {
      const captured = record.variants[variant];
      if (!captured) {
        console.warn(
          `[docs-site] ${id} has a ${variant} render but no ${variant} layout — ` +
            'that cell stays a screenshot. Regenerate the fixtures.',
        );
        continue;
      }
      writeFileSync(
        join(shotDest, `${id}-${variant}.json`),
        JSON.stringify({ size: captured.size, shapes: captured.shapes }),
      );
    }
  }
}

/**
 * Every PNG carries its own dimensions in the IHDR chunk, which always
 * starts at byte 16 of a valid PNG. Reading them beats recording them:
 * a number stored beside the image can disagree with the image, and this
 * one cannot.
 */
/** os -> appearance -> the render for that cell. */
type RenderGrid = Record<string, Record<string, { file: string; width: number; height: number }>>;

function readPngSize(file: string): { width: number; height: number } | null {
  try {
    const head = readFileSync(file).subarray(0, 24);
    if (head.length < 24 || head.readUInt32BE(0) !== 0x89504e47) return null;
    return { width: head.readUInt32BE(16), height: head.readUInt32BE(20) };
  } catch {
    return null;
  }
}

/**
 * A fixture's `layout.json`, as far as this file reads it: the two fields a
 * human authored on the fixture, and the per-variant captures the site
 * republishes as geometry for `<secreq-window>`.
 *
 * The digest beside each capture is not here. It is the Rust suite's short
 * answer to "did anything move", and nothing outside that suite can act on it.
 */
interface FixtureRecord {
  window?: string;
  caption?: string;
  variants?: Record<string, { size: unknown; shapes: unknown }>;
}

/**
 * `02-single-pending/macos-dark.png`
 *   -> `["02-single-pending", "macos", "dark"]`.
 */
function parseRenderPath(render: string): [string, string, string] | null {
  const match = render.match(/^(.+)\/(macos|windows|gnome)-(dark|light)\.png$/);
  return match ? [match[1], match[2], match[3]] : null;
}

/**
 * What a fixture declares about itself, out of its `layout.json`.
 *
 * Read twice per build — once for the two authored strings the screenshot
 * index needs, once for the geometry the windows need — because the
 * alternative is threading a hundred kilobytes of shapes through a function
 * whose subject is captions. JSON has no partial read either way, and both
 * passes together cost less than a tenth of a second across the corpus.
 */
function readFixtureRecord(shotSrc: string, id: string): FixtureRecord | null {
  try {
    return JSON.parse(readFileSync(join(shotSrc, id, 'layout.json'), 'utf-8'));
  } catch {
    return null;
  }
}

/**
 * Build the screenshot index the app imports, from the tree and the PNGs.
 *
 * Almost everything here is *derived*: a render's path carries its own
 * coordinates (`<id>/<os>-<appearance>.png`), and every PNG carries its own
 * dimensions, so the grid needs nothing written down. The only things that
 * cannot be derived are the two a human authored on the fixture in
 * `tests/ui_screenshots.rs` — the window kind and the caption — and those come
 * out of the `layout.json` the harness writes into the fixture's own folder.
 *
 * A fixture whose renders exist but whose `layout.json` does not still
 * publishes; it just arrives unlabelled and uncaptioned. That is a half-blessed
 * tree rather than a normal state, so it warns.
 */
function writeShotIndex(shotSrc: string, renders: string[]) {
  const index: Record<string, { window?: string; caption?: string; renders: RenderGrid }> = {};

  // Read from the foldered source, publish under the flat public name: the
  // grid the site consumes only ever speaks in URLs.
  for (const render of renders) {
    const parsed = parseRenderPath(render);
    if (!parsed) continue;
    const [id, os, appearance] = parsed;
    const size = readPngSize(join(shotSrc, render));
    if (!size) continue;
    const entry = (index[id] ??= { renders: {} });
    (entry.renders[os] ??= {})[appearance] = { file: publicName(render), ...size };
  }

  const unrecorded: string[] = [];
  for (const [id, entry] of Object.entries(index)) {
    const record = readFixtureRecord(shotSrc, id);
    if (!record) {
      unrecorded.push(id);
      continue;
    }
    entry.window = record.window;
    entry.caption = record.caption;
  }
  if (unrecorded.length > 0) {
    console.warn(
      `[docs-site] ${unrecorded.length} screenshot fixture(s) have no layout.json ` +
        `(${unrecorded.join(', ')}) — they publish without a caption or frame ` +
        'label until the fixtures are regenerated: ' +
        '`SECREQ_BLESS_SHOTS=1 cargo test --test ui_screenshots -- --test-threads=1`',
    );
  }

  const outDir = join(process.cwd(), '.generated');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'shots.json'), JSON.stringify(index, null, 2) + '\n');
}

export default defineConfig({
  base: process.env.BASE_URL || '/',
  plugins: [copyRepoAssets(), vike(), react(), tailwindcss()],
  server: {
    // Bind every interface, not just loopback, so the dev site is reachable
    // from a phone or a second machine on the same network — which is the
    // only way to check that a consent window rendered from layout data, or
    // a terminal recording sized to 80 columns, survives a real small screen
    // rather than a desktop browser pretending to be one.
    //
    // This is the *docs* dev server: it serves prose, screenshots and their
    // geometry, and holds nothing a reader of the docs site could not already
    // read. It still means anyone on the network can reach it while it runs,
    // so it is a dev-server setting and has no bearing on what ships.
    host: true,
  },
  build: {
    rollupOptions: {
      external: ['/pagefind/pagefind.js'],
    },
  },
  ssr: {
    external: ['gray-matter', 'shiki'],
  },
});
