import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import vike from 'vike/plugin';
import { defineConfig, type Plugin } from 'vite';

/**
 * Mirror repo-owned assets into `public/` at the start of every dev/build run.
 *
 * Both sources are owned by other tickets; we only READ them, and both
 * destinations are gitignored build artifacts, so nothing is duplicated in
 * source control.
 *
 *   `docs/*.schema.json`        -> `/schemas/*.json`
 *     Stable static URLs an editor's `$schema` key can point at.
 *
 *   `dev-docs/ui-screenshots/*` -> `/ui/*.png`
 *     The screenshot fixtures generated by `tests/ui_screenshots.rs`. The docs
 *     illustrate themselves with the same PNGs the test harness renders, so a
 *     screenshot can never drift from the UI it documents — regenerating the
 *     fixtures republishes the docs images.
 */
function copyRepoAssets(): Plugin {
  return {
    name: 'secreq-copy-repo-assets',
    buildStart() {
      const repoRoot = join(process.cwd(), '..');
      const publicDir = join(process.cwd(), 'public');

      const schemaDest = join(publicDir, 'schemas');
      mkdirSync(schemaDest, { recursive: true });
      for (const file of ['wraps.schema.json', 'auto-rules.schema.json']) {
        try {
          copyFileSync(join(repoRoot, 'docs', file), join(schemaDest, file));
        } catch {
          console.warn(`[docs-site] Could not copy schema ${file}`);
        }
      }

      const shotSrc = join(repoRoot, 'dev-docs', 'ui-screenshots');
      const shotDest = join(publicDir, 'ui');
      mkdirSync(shotDest, { recursive: true });

      let files: string[] = [];
      try {
        files = readdirSync(shotSrc).filter((file) => file.endsWith('.png'));
      } catch {
        console.warn(`[docs-site] Could not read screenshots from ${shotSrc}`);
      }

      // Mirror, don't merge. Copying without pruning meant a renamed or
      // deleted fixture kept being published forever — the destination is a
      // gitignored build artifact, so it should reflect the source exactly
      // rather than accumulate every render this checkout has ever seen.
      const wanted = new Set(files);
      for (const stale of readdirSync(shotDest)) {
        if (!wanted.has(stale)) rmSync(join(shotDest, stale), { force: true });
      }
      for (const file of files) {
        copyFileSync(join(shotSrc, file), join(shotDest, file));
      }
      if (files.length === 0) {
        console.warn('[docs-site] No UI screenshots copied — figures will 404');
      }

      writeShotIndex(shotSrc, files);
      writeTermIndex(join(repoRoot, 'dev-docs', 'cli-transcripts'));
    },
  };
}

/**
 * Bundle the recorded terminal sessions for the app to import.
 *
 * Unlike screenshots there is no manifest to join against: each recording
 * is one self-describing JSON written by `tests/cli_transcripts.rs`, so the
 * index is just those files keyed by id. The `.txt` companions beside them
 * are for reviewing diffs and are deliberately not published.
 */
function writeTermIndex(termSrc: string) {
  const index: Record<string, unknown> = {};

  let files: string[] = [];
  try {
    files = readdirSync(termSrc).filter((file) => file.endsWith('.json'));
  } catch {
    console.warn(
      '[docs-site] No CLI transcripts yet — record them with ' +
        '`cargo test --test cli_transcripts -- --ignored --test-threads=1`.'
    );
  }

  for (const file of files) {
    try {
      const doc = JSON.parse(readFileSync(join(termSrc, file), 'utf-8'));
      const id = doc.id ?? file.replace(/\.json$/, '');
      index[id] = doc;
    } catch {
      console.warn(`[docs-site] Could not read transcript ${file}`);
    }
  }

  const outDir = join(process.cwd(), '.generated');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'terms.json'), JSON.stringify(index, null, 2) + '\n');
}

/**
 * Every PNG carries its own dimensions in the IHDR chunk, which always
 * starts at byte 16 of a valid PNG. Reading them beats recording them:
 * a number stored beside the image can disagree with the image, and this
 * one cannot.
 */
/** os -> appearance -> the render for that cell. */
type RenderGrid = Record<string, Record<string, { file: string; width: number; height: number }>>;

function readPngSize(file: string): { width: number; height: number } | null {
  try {
    const head = readFileSync(file).subarray(0, 24);
    if (head.length < 24 || head.readUInt32BE(0) !== 0x89504e47) return null;
    return { width: head.readUInt32BE(16), height: head.readUInt32BE(20) };
  } catch {
    return null;
  }
}

/** One fixture's entry in the harness-written manifest. */
interface ManifestEntry {
  window?: string;
  caption?: string;
  /** os -> appearance -> PNG filename. */
  renders?: Record<string, Record<string, string>>;
}

/** `02-single-pending-macos-dark` -> `["02-single-pending", "macos", "dark"]`. */
function parseRenderName(stem: string): [string, string, string] | null {
  const match = stem.match(/^(.*)-(macos|windows|gnome)-(dark|light)$/);
  return match ? [match[1], match[2], match[3]] : null;
}

/**
 * Join what the screenshot harness recorded to what the PNGs themselves
 * report, and emit the result for the app to import.
 *
 * `manifest.json` is written by `tests/ui_screenshots.rs` as it renders, so
 * the window kind, OS flavour, caption and the set of appearance renders all
 * come from the code that produced them. Nothing about a screenshot is
 * described twice, and nothing here needs editing when a fixture changes.
 *
 * The manifest only exists once the harness has been run. Before that, the
 * PNGs on disk are indexed on their own so the site still builds — just
 * without captions or frame labels.
 */
function writeShotIndex(shotSrc: string, files: string[]) {
  let manifest: Record<string, ManifestEntry> = {};
  try {
    manifest = JSON.parse(readFileSync(join(shotSrc, 'manifest.json'), 'utf-8'));
  } catch {
    console.warn(
      '[docs-site] No screenshot manifest yet — regenerate the fixtures with ' +
        '`cargo test --test ui_screenshots -- --ignored --test-threads=1` ' +
        'to pick up captions, frame labels and light-appearance renders.'
    );
  }

  const present = new Set(files);
  const index: Record<string, { window?: string; caption?: string; renders: RenderGrid }> = {};

  // Filenames spoken for by a manifest entry, so the catch-up pass below
  // does not re-file a render that already belongs to a fixture's grid.
  const claimed = new Set<string>();

  const put = (id: string, os: string, appearance: string, file: string) => {
    const size = readPngSize(join(shotSrc, file));
    if (!size) return;
    const entry = (index[id] ??= { renders: {} });
    (entry.renders[os] ??= {})[appearance] = { file, ...size };
  };

  for (const [id, entry] of Object.entries(manifest)) {
    for (const [os, byAppearance] of Object.entries(entry.renders ?? {})) {
      for (const [appearance, file] of Object.entries(byAppearance)) {
        claimed.add(file);
        // A cell the harness recorded but never wrote — or wrote under an
        // older name — is dropped rather than published as a broken <img>.
        if (present.has(file)) put(id, os, appearance, file);
      }
    }
    if (index[id]) {
      index[id].window = entry.window;
      index[id].caption = entry.caption;
    }
  }

  // Renders the manifest has not caught up with. Filenames carry their own
  // coordinates (`<id>-<os>-<appearance>.png`), so a fixture added since the
  // last full regeneration still lands in the right grid — it just arrives
  // without a caption until the manifest is rewritten.
  for (const file of files) {
    if (claimed.has(file)) continue;
    const parsed = parseRenderName(file.replace(/\.png$/, ''));
    if (!parsed) continue;
    const [id, os, appearance] = parsed;
    if (manifest[id]) continue;
    put(id, os, appearance, file);
  }

  const outDir = join(process.cwd(), '.generated');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'shots.json'), JSON.stringify(index, null, 2) + '\n');
}

export default defineConfig({
  base: process.env.BASE_URL || '/',
  plugins: [copyRepoAssets(), vike(), react(), tailwindcss()],
  build: {
    rollupOptions: {
      external: ['/pagefind/pagefind.js'],
    },
  },
  ssr: {
    external: ['gray-matter', 'shiki'],
  },
});
