//! Guards the public distribution channels against drift from the release
//! build matrix and the crate version. These are hand-maintained text
//! artifacts that a reviewer can't easily eyeball for mutual consistency:
//!
//!   - `.github/workflows/release.yml` cross-compiles four target triples.
//!   - `dist/install.sh` maps `uname` output onto those same triples.
//!   - `dist/homebrew/gen-formula.sh` links the release tarball for each
//!     triple. Nothing is committed: the generator is run here and its output
//!     asserted on, so release-plz bumping the crate version cannot leave a
//!     checked-in formula behind (see the section comment below).
//!   - `Cargo.toml` carries the crates.io metadata, and `release-plz.toml`
//!     plus `release.yml` decide which of them publishes.
//!
//! When they fall out of lockstep the failure surfaces at a stranger's install
//! time — a 404 tarball, an "unsupported arch", or a `cargo publish`
//! rejection — long after the release shipped. These tests fail the build
//! instead. See brain: areas/secreq/releasing.md and docs/install.md.

use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn read(path: &str) -> String {
    fs::read_to_string(path).unwrap_or_else(|e| panic!("{path}: {e}"))
}

/// The release build matrix is the single source of truth for which platforms
/// secreq ships prebuilt binaries for; every other channel must cover exactly
/// these four target triples.
fn release_targets() -> Vec<String> {
    let yml = read("../../.github/workflows/release.yml");
    let mut targets: Vec<String> = yml
        .lines()
        .filter_map(|l| l.trim().strip_prefix("- target:"))
        .map(|t| t.trim().to_owned())
        .collect();
    targets.sort();
    targets.dedup();
    assert_eq!(
        targets.len(),
        4,
        "expected 4 release targets, got {targets:?}"
    );
    targets
}

/// `arch-rest` split of a target triple:
/// `x86_64-unknown-linux-gnu` -> ("x86_64", "unknown-linux-gnu").
fn split_target(triple: &str) -> (&str, &str) {
    match triple.split_once('-') {
        Some(parts) => parts,
        None => panic!("target triple {triple:?} must have an arch- prefix"),
    }
}

/// The installer builds each triple from an arch token and an OS token rather
/// than hard-coding the four full strings, so assert both halves of every
/// release target appear in the script. A target the build matrix gains but
/// the installer's `case` arms don't handle leaves those users with an
/// "unsupported" error against a binary that exists.
#[test]
fn installer_covers_every_release_target() {
    let sh = read("../../dist/install.sh");
    for triple in release_targets() {
        let (arch, rest) = split_target(&triple);
        assert!(sh.contains(arch), "install.sh omits arch token {arch:?}");
        assert!(sh.contains(rest), "install.sh omits OS token {rest:?}");
    }
}

// ── The Homebrew formula ──────────────────────────────────────────────────
//
// There is no committed `.rb`. `dist/homebrew/gen-formula.sh` is the only copy
// of the formula, and these tests run it rather than reading a checked-in
// artifact.
//
// That is not a style preference. A committed formula names a concrete version,
// so it has to be regenerated by hand every time release-plz bumps the crate in
// a release PR — and release-plz knows nothing about a `.rb`. The result was a
// release PR that failed its own CI on these very tests, and whose hand-fix was
// then clobbered the next time release-plz force-pushed the branch. Testing the
// generator's output removes the second copy rather than trying to keep it in
// step.

/// Run the generator the way `release.yml` does: `bash` against a repo-relative
/// script path, from the repo root. A generator that quietly grew a dependency
/// on its working directory fails here rather than during a release.
fn run_generator(args: &[&str]) -> std::process::Output {
    Command::new("bash")
        .arg("dist/homebrew/gen-formula.sh")
        .args(args)
        .current_dir("../..")
        .output()
        .expect("gen-formula.sh should be runnable with bash")
}

fn generate_formula(args: &[&str]) -> String {
    let out = run_generator(args);
    assert!(
        out.status.success(),
        "gen-formula.sh {args:?} failed: {}",
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).expect("the formula should be UTF-8")
}

/// Write a `SHA256SUMS` listing `targets`, in the layout `sha256sum ./*.tar.gz`
/// produces, and return its path alongside the digests used.
fn manifest_for(tag: &str, version: &str, targets: &[String]) -> (PathBuf, Vec<String>) {
    let dir = std::env::temp_dir().join(format!("secreq-dist-{tag}-{}", std::process::id()));
    fs::create_dir_all(&dir).expect("temp dir should be creatable");
    let digests: Vec<String> = (0..targets.len())
        .map(|i| {
            std::char::from_digit(i as u32 + 1, 16)
                .expect("index fits a hex digit")
                .to_string()
                .repeat(64)
        })
        .collect();
    let body: String = targets
        .iter()
        .zip(&digests)
        .map(|(t, d)| format!("{d}  ./secreq-{version}-{t}.tar.gz\n"))
        .collect();
    let path = dir.join("SHA256SUMS");
    fs::write(&path, body).expect("manifest should be writable");
    (path, digests)
}

/// The formula links a concrete tarball per target; every release target must
/// have its download URL, or `brew install` 404s on that arch.
#[test]
fn homebrew_formula_links_every_release_target() {
    let version = env!("CARGO_PKG_VERSION");
    let formula = generate_formula(&["--version", version]);
    for triple in release_targets() {
        let asset = format!("secreq-{version}-{triple}.tar.gz");
        assert!(
            formula.contains(&asset),
            "the generated formula is missing the URL for {asset}"
        );
    }
}

/// The generator must stamp the version it is handed. A template that hardcoded
/// one would point Homebrew at tarballs from whichever release it was written
/// against, forever.
#[test]
fn homebrew_formula_names_the_version_it_is_given() {
    let version = env!("CARGO_PKG_VERSION");
    let formula = generate_formula(&["--version", version]);
    let needle = format!("version \"{version}\"");
    assert!(
        formula.contains(&needle),
        "the generated formula does not declare {needle:?}"
    );
}

/// Every `sha256 "…"` must be a 64-char hex digest. Without a manifest that is
/// the all-zero sentinel the release workflow overwrites with real digests. A
/// malformed one — a truncated paste, a leftover placeholder word — makes
/// `brew install` reject the download.
#[test]
fn homebrew_formula_shas_are_wellformed() {
    let formula = generate_formula(&["--version", env!("CARGO_PKG_VERSION")]);
    let mut seen = 0;
    for line in formula.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("sha256 \"") {
            let digest = rest.strip_suffix('"').unwrap_or(rest);
            assert_eq!(digest.len(), 64, "sha256 {digest:?} is not 64 chars");
            let all_hex = digest.chars().all(|c| c.is_ascii_hexdigit());
            assert!(all_hex, "sha256 digest is not hex: {digest:?}");
            seen += 1;
        }
    }
    assert_eq!(
        seen, 4,
        "expected 4 sha256 digests in the formula, got {seen}"
    );
}

/// A full manifest's digests must reach the formula — otherwise the refusal
/// test below would pass against a generator that had simply stopped reading
/// manifests at all.
#[test]
fn homebrew_formula_takes_its_digests_from_the_manifest() {
    let version = env!("CARGO_PKG_VERSION");
    let targets = release_targets();
    let (manifest, digests) = manifest_for("full", version, &targets);

    let formula = generate_formula(&[
        "--version",
        version,
        "--checksums",
        manifest.to_str().expect("temp path should be UTF-8"),
    ]);
    fs::remove_dir_all(manifest.parent().expect("manifest has a parent")).ok();

    for digest in digests {
        assert!(
            formula.contains(&digest),
            "the manifest digest {digest} did not reach the formula"
        );
    }
    assert!(
        !formula.contains(&"0".repeat(64)),
        "a real manifest still produced a sentinel digest"
    );
}

/// A manifest missing a target must fail the generator, not yield a formula
/// with a hole in it.
///
/// `sha_for` reports the miss and calls `exit 1`, but it used to be called from
/// a command substitution inside the heredoc that prints the formula — so the
/// exit ended that *subshell* and `set -e` never saw it. The formula was printed
/// with an empty `sha256 ""` and the generator exited 0, so the release step
/// called it a success and pushed a formula Homebrew refuses to install from,
/// the only trace being an error line partway down a green log. The digests are
/// resolved into variables before the heredoc now, where a failed substitution
/// in an assignment does trip `set -e`.
#[test]
fn homebrew_formula_refuses_a_manifest_with_a_target_missing() {
    let version = env!("CARGO_PKG_VERSION");
    let mut targets = release_targets();
    let dropped = targets.pop().expect("the matrix has targets");
    let (manifest, _) = manifest_for("partial", version, &targets);

    let out = run_generator(&[
        "--version",
        version,
        "--checksums",
        manifest.to_str().expect("temp path should be UTF-8"),
    ]);
    fs::remove_dir_all(manifest.parent().expect("manifest has a parent")).ok();

    let formula = String::from_utf8_lossy(&out.stdout);
    assert!(
        !formula.contains("sha256 \"\""),
        "the generator emitted an empty digest for {dropped} instead of failing:\n{formula}"
    );
    assert!(
        !out.status.success(),
        "the generator exited 0 with no digest for {dropped}; the release step would \
         call that a success and push the formula"
    );
}

/// Extract the quoted-string array assigned to `key` in Cargo.toml (the
/// values live on a single line).
fn cargo_string_array(key: &str) -> Vec<String> {
    let cargo = read("Cargo.toml");
    let prefix = format!("{key} = [");
    let line = cargo
        .lines()
        .find(|l| l.trim_start().starts_with(prefix.as_str()))
        .unwrap_or_else(|| panic!("Cargo.toml has no `{key} = [...]` array"));
    // Odd-indexed `split('"')` fields are the contents between quote pairs.
    let quoted = line.split('"').skip(1).step_by(2);
    quoted.map(str::to_owned).collect()
}

/// crates.io rejects a publish whose manifest breaks its metadata rules, and
/// the rejection only shows up when the maintainer runs the release. Assert
/// the constraints locally: keywords capped at 5 and 20 chars each, categories
/// present, and the descriptive fields `cargo install` users rely on set.
#[test]
fn crate_metadata_is_crates_io_publishable() {
    let cargo = read("Cargo.toml");

    let keywords = cargo_string_array("keywords");
    assert!(
        (1..=5).contains(&keywords.len()),
        "crates.io allows at most 5 keywords, found {}: {keywords:?}",
        keywords.len()
    );
    for kw in &keywords {
        assert!(
            !kw.is_empty() && kw.len() <= 20,
            "bad keyword length: {kw:?}"
        );
        let starts_alnum = kw.starts_with(|c: char| c.is_ascii_alphanumeric());
        assert!(starts_alnum, "keyword must start alphanumeric: {kw:?}");
    }

    let categories = cargo_string_array("categories");
    assert!(
        !categories.is_empty(),
        "declare at least one crates.io category"
    );

    for field in ["readme", "repository", "homepage", "license", "description"] {
        let decl = format!("{field} = ");
        let present = cargo.lines().any(|l| l.trim_start().starts_with(&decl));
        assert!(present, "Cargo.toml [package] is missing `{field}`");
    }
}

/// `cargo install secreq` only works if a release actually pushes the crate,
/// and exactly one thing must do it.
///
/// release-plz would publish from the runner that opens the release PR, using
/// a stored registry token. It is turned off so the crate ships from
/// `release.yml`'s `publish-crate` job instead, which mints a short-lived
/// crates.io token from GitHub's OIDC identity and runs only after the signed
/// binaries are out.
///
/// Both halves are asserted because either one alone fails quietly. Delete the
/// workflow job and nothing publishes; flip release-plz back on and the crate
/// ships from a commit CI never verified, before the tag exists.
#[test]
fn exactly_one_thing_publishes_to_crates_io() {
    let plz = read("../../release-plz.toml");
    assert!(
        plz.lines().any(|l| l.trim() == "publish = false"),
        "release-plz.toml must set `publish = false`; the crate is published \
         by release.yml's publish-crate job, over OIDC"
    );

    let yml = read("../../.github/workflows/release.yml");
    assert!(
        yml.contains("publish-crate:"),
        ".github/workflows/release.yml must keep the `publish-crate` job, or \
         nothing publishes the crate at all"
    );
    assert!(
        yml.contains("cargo publish"),
        "the publish-crate job must actually run `cargo publish`"
    );
    assert!(
        yml.contains("crates-io-auth-action"),
        "publish-crate must mint its token over OIDC rather than read a \
         stored CARGO_REGISTRY_TOKEN"
    );
}
